import "./globals.css";
import { Kanit } from "next/font/google";
import clsx from "clsx";
import NextAuthProvider from "@/components/NextAuthProvider";
import NavBar from "@/components/NavBar";
const kanit = Kanit({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin", "thai"],
});

export const metadata = {
  title: "Book Store",
  description: "Generated by thanachai aktananan.",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
  session: any;
}) {
  return (
    <html lang="en">
      <body className={clsx(kanit.className)}>
        <NextAuthProvider>
          <NavBar />
          {children}
        </NextAuthProvider>
      </body>
    </html>
  );
}
